default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: development_instarails

test:
  <<: *default
  database: test_instarails

production:
  <<: *default
  database: production_instarails
